export const ActionTypes = {
  GET_CATEGORY: "GET_CATEGORY",
  GET_PRODUCTS: "GET_PRODUCTS",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_AUTH_ERRORS: "GET_AUTH_ERRORS",

  CREATE_USER: "CREATE_USER",

  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
