export const ActionTypes = {
  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_DETAILS: "GET_CATEGORY_DETAILS",
  GET_CART_DETAILS: "GET_CART_DETAILS",

  GET_ADS: "GET_ADS",
  GET_REVIEW: "GET_REVIEW",

  CREATE_USER: "CREATE_USER",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_AUTH_ERRORS: "GET_AUTH_ERRORS",

  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  GET_BRANDS:"GET_BRANDS",
  GET_SHOPS:"GET_SHOPS",

  GET_ORDERS:"GET_ORDERS"
};
